import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Navbar from "./_components/Navbar";
import Footer from "./_sections/Footer";

export const metadata: Metadata = {
  title: "W-SZ Portfolio",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/images/fav.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="dark">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
